name: Build

on:
  workflow_call:
    inputs:
      jdk:
        type: number
        default: 11
      goals:
        type: string
        default: 'clean package'
    secrets:
      PACKAGES_TOKEN:
        required: true
      ORIGIN_PACKAGES_TOKEN:
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        overwrite-settings: false
        java-version: ${{ inputs.jdk }}
    - name: Configure Maven
      run: |
        mkdir -p ~/.m2
        echo "<settings>
                <servers>
                  <server><id>github</id><username>x-access-token</username><password>${{ secrets.GITHUB_TOKEN }}</password></server>
                  <server><id>github-dkk-v2</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-dkk-okonomi</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-dkk-google-recaptcha</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-dkk-smartsend</id><username>x-access-token</username><password>${{ secrets.PACKAGES_TOKEN }}</password></server>
                  <server><id>github-origin-legacy</id><username>x-access-token</username><password>${{ secrets.ORIGIN_PACKAGES_TOKEN }}</password></server>
                  <server><id>github-origin-gt-legacy</id><username>x-access-token</username><password>${{ secrets.ORIGIN_PACKAGES_TOKEN }}</password></server>
                  <server><id>github-origin-seamless-mail</id><username>x-access-token</username><password>${{ secrets.ORIGIN_PACKAGES_TOKEN }}</password></server>
                  <server><id>github-origin-seamless-email</id><username>x-access-token</username><password>${{ secrets.ORIGIN_PACKAGES_TOKEN }}</password></server>
                </servers>
              </settings>" > ~/.m2/settings.xml
    - name: Cache maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B ${{ inputs.goals }} --file pom.xml
